### PR TITLE
Removed unassigned assets.

### PR DESCRIPTION
**Pull request by skylarsch**
By removing these images it fixes the `warning: Ambiguous Content: The image set “xyz” has an unassigned image.` being thrown by “Asset Catalog Compiler.”

### CODE REVIEW

**Comment by radazzouz** [comment]
Hi @skylarsch,

Thanks for taking the time to reach out to us :+1: 

Our designer created `@3x` assets so that the can be used in the future. Apparently Xcode doesn't like `@3x` assets for the iPad (yet). We prefer to keep them there even if they generate warnings hoping that one day we'll have an `@3x` iPad :wink: 

If you have the `GCC_TREAT_WARNINGS_AS_ERRORS` complier flag enabled, we suggest that you make this change locally.

I'll be closing this PR for now.

Thanks!

**Comment by skylarsch** [comment]
No problem.

**Comment by tewha** [comment]
Can I suggest putting them somewhere else that won't cause the warning? You could put them in an Unused folder somewhere, or even put them off in a branch only available as a pull request.

Even if there is a 3x iPad one day, it isn't worth the warnings now.

**Comment by radazzouz** [comment]
Hi @tewha,

Thanks for the comment :+1: 

It seems that the `@3x` iPad image is not the only xcasset warning. I just noticed that more xcassets warnings cropped recently. Especially in **ACME Browser** and **ACME Browser 2** with the most recent Mac App Store version of Xcode. So I fixed them in PR #196. :smile:

Cheers!

**Pull request closed without merging**
