### PR TITLE
UIWebView deprecation

### LINKED ISSUE #414: UIWebView deprecation
Apple is now attaching this warning to any app store uploads whose binaries contain the string `UIWebView`:

> **ITMS-90809: Deprecated API Usage** - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

For now, it's just a warning, and doesn't stop the upload from going through. I don't have enough context on how XCode/App Store Connect finds the references to `UIWebView` to know if gating the `UIWebView` stuff behind a preprocessor macro would work, but I suspect it would.

### PR DESCRIPTION
**Pull request by rudyrichter**
This commit does several things:
* Moves all projects forward to Xcode 11 format
* Updates build settings and localization targets
* Converts swift projects to Swift 5
* Moves the bar forward from iOS 7 to iOS 9
* Removes all support for UIWebView
* Removes the deprecated call `- (void)fillLoginIntoWebView:(nonnull id)webView forViewController:(nonnull UIViewController *)viewController sender:(nullable id)sender completion:(nonnull OnePasswordSuccessCompletionBlock)completion;`
* Updates Readme.md urls, removes mention of a newsletter

Resolves: #414, #409, #369

### CODE REVIEW

**Review by kevinbhayes — APPROVED** [review]

**Comment by Ashoat** [comment]
Thanks for making this PR @rudyrichter! I can't seem to find the new v1.8.6 of this CocoaPod online. Wondering if the release will happen soon or if there is an alternative way to pull the CocoaPod directly from GitHub.

**Comment by mccarron** [comment]
> Thanks for making this PR @rudyrichter! I can't seem to find the new v1.8.6 of this CocoaPod online. Wondering if the release will happen soon or if there is an alternative way to pull the CocoaPod directly from GitHub.

Doesn't look like @rudyrichter and team have pushed the lastest version to Cocoapods Trunk yet, but until then you can grab it this way: 

> pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'master'

It works great, so thanks all around!

**Comment by jbmorley** [comment]
Good catch, thank you! In the end, I think it's probably best to remove this anyhow--iOS now has built-in support for password management, and it removes a dependency on third-party code. Hopefully that trend can continue too.

**Review by whiteslack — APPROVED** [review]

**Review by Sarkar44 — COMMENTED** [review]
review change

**Review by Sarkar44 — COMMENTED** [review]
approve

**Review by LadyE215 — COMMENTED** [review]
[null]()

**Review by LadyE215 — COMMENTED** [review]
Thanks

**Pull request merged**
