### PR TITLE
Add Swift version of the extension and a demo app

### PR DESCRIPTION
**Pull request by ghecho**
Important note: Due to the limitations of Swift (lack of conditional compiling) and in the hope of cleaning the code I decided to support only iOS 8 AND WKWebView (UIWebView has some issues: http://nshipster.com/wkwebkit/). 

Currently the Demo App only supports login, I plan to add change password and register in the future but feel free to add them if you like. Also, I have only tested the login part of the extension (and in doing that I discovered 2 errors in my code) so be aware of possible bugs in other parts of the code which are untested by now.

I tried to mimic the style and respect the project structure (ex. add the swift project alongside the others in the workspace, naming the bundle identifier to match the others, etc ) but let me know if something needs changing.

Example of usage:

```swift
@IBAction func onePasswordTapped() {
	OnePasswordExtension.sharedInstance.findLoginWithURLString("https://www.acme.com", viewController: self, sender: self, completion: { (loginDict, error) in
		if loginDict == nil {
			if error!.code != AppExtensionErrorCodeCancelledByUser {
				NSLog("Error invoking 1Password App Extension for find login: %@", error!)
			}
			return
		}
		
		self.usernameText.text = loginDict![AppExtensionUsernameKey] as String
		self.passwordText.text = loginDict![AppExtensionPasswordKey] as String
	})
}
```

### CODE REVIEW

**Comment by radazzouz** [comment]
Hi @ghecho,

Thanks so much for the "Swift initiative" :+1:

I checked out your branch and it works fine so far. Good job! 

However, we cannot merge it to master as it is right now. And here's why:

1. We should keep using the Objective-C `OnePasswordExtension` class for the Swift demo apps too. This way the code is more maintainable and we won’t have to duplicate work when making changes.

2. By the looks of it, you are planning on “Swift-icising” (I just invented a word.YAY!) the demo apps in separate/several phases/PRs, so I published a new branch, [add-Swift-support](https://github.com/AgileBits/onepassword-app-extension/tree/add-Swift-support). Could you please change the destination branch for your PR to this branch instead of master? So that when we finish all three demo apps (**ACME**, **ACME Browser** and **ACME Browser 2**) we’ll PR this branch to master.

Please let me know if there's anything else I can do to help :smiley:

Cheers!

**Comment by ghecho** [comment]
Hi @radazzouz,

Sure, I'll do that later and, in fact, that issue crossed my mind when I was doing it but I figured that it was a nice exercise in any case.

I'll let you know.
Cheers!

**Comment by ghecho** [comment]
One more thing, I'm not sure that I can "edit" the PR to change the branch so I'll close it and open a new one, I hope this is ok.

**Comment by radazzouz** [comment]
Hi @ghecho,

Thanks so much for being so quick!

I just noticed that you closed PR #192 and opened PR #194, which great!

Cheers!

**Pull request closed without merging**
