### PR TITLE
Converted to swift 3 syntax

### PR DESCRIPTION
**Pull request by krider2010**
Also updated some of the code to be more “swifty”.

### CODE REVIEW

**Comment by gks** [comment]
Hi @krider2010 

Thanks for taking the time to do this! You might be interested in Issue #329 and the corresponding [branch](https://github.com/AgileBits/onepassword-app-extension/tree/new/ios10). 

There is [an explanation](https://github.com/AgileBits/onepassword-app-extension/issues/329#issuecomment-251200759) in that Issue as to why we have not yet moved to Swift 3 and why we're holding off on making that transition to `master` until a later date. If you have any changes you'd like to see to `new/ios10`, please feel free to PR them against it.

For now though I think this PR will get closed. I hope you'll agree.

**Comment by krider2010** [comment]
So I'm clear, I can make this PR for swift 3 against the `new/iOS10` branch? I really think having example code for swift 3 is important. Everyone I know, even commercially, is now biting the bullet and dealing with swift 3 given that Apple will flip the switch within the Xcode 8 lifecycle.

**Comment by gks** [comment]
@krider2010 You can definitely PR against it if you think it fits the topic. I'm not sure I can promise it'll be merged, but I'm happy to take a look at it against that branch instead.

**Comment by krider2010** [comment]
Fair enough!

**Comment by gks** [comment]
Thanks! Closing this PR :)

**Pull request closed without merging**
