### PR TITLE
Update constraints for iPhone screen so the "Sign Up" button is visible

### PR DESCRIPTION
**Pull request by ghecho**
The sign up button was not appearing so I moved it a bit to the top (I didn't move the hidden textfield of the one time generated password).

### CODE REVIEW

**Comment by radazzouz** [comment]
Looks good @ghecho! :+1: 

Can you please make the same change to the Onjective-C storyboard for ACME?

Thanks!

**Comment by ghecho** [comment]
Sure. I will and I'll submit a PR

**Comment by radazzouz** [comment]
You could do it it in this very PR. No need for another :wink:

**Comment by ghecho** [comment]
Sure. Didn't think of that, I'll do that. 👍

**Comment by ghecho** [comment]
I just pushed the Objective-C layout fix but I just noticed that somehow there're some conflicts. Do you have any idea of why? I'm investigating right now.

**Comment by ghecho** [comment]
I think I now know. I think you pushed some changes after I made my changes. I'll try to resolve this so it can be automatically merged unless you have a better idea.

**Comment by ghecho** [comment]
I did a force-push with the fix right now. 

Here're my steps: 
- "save" the 2 commits by tagging them
- revert to your last known commit
- pull the rest of your commits
- cherry pick my 2 commits
- force push to my branch

**Comment by ghecho** [comment]
Also I had to fix a merge conflict with some internal version of the storyboard (it's super fun to manage this Xcode file changes in git) but I did tried both versions and they seemed to be working, in any case, let me know what you think.

**Comment by radazzouz** [comment]
Thanks so much for helping out @ghecho :+1: 

The PR looks good now. I'll merge it!

Cheers!

**Comment by ghecho** [comment]
Sure, happy to help.

Cheers!

**Pull request merged**
