### PR TITLE
Audits extension for nullability

### PR DESCRIPTION
**Pull request by tapi**
Extension is now audited for nullability, assumes non null for the file as a whole and annotates specific items that are nullable.
should improve usage in Swift

### CODE REVIEW

**Comment by radazzouz** [comment]
Thank @tapi! :+1:

**Comment by tapi** [comment]
Added a nil assertion in one of the methods since the documentation specified that it must be nonnull.

**Comment by radazzouz** [comment]
**Tests:**

* I changed **ACME's** Base SDK and the deployment target to iOS 7.1.
* I used Xcode 5.1.1 to

**Result:**

* Warnings and build errors.

@tapi, could you please make sure that **ACME** successfully builds on iOS 7 devices?

I labeled this PR as in progress for now.

Thanks!

**Comment by tapi** [comment]
You're still supporting Xcode 5? I can add macro polyfills for the nullability stuff but it should work on Xcode 6 with iOS7 as a deployment target.

**Comment by radazzouz** [comment]
Thanks for responding so quickly, @tapi! You're Awesome!

I use Xcode 5 to test compatibility with iOS 7.1 and earlier. I also tested with Xcode 6 and it all seems to work fine now. Merging right now!

Cheers!

**Pull request merged**
