### PR TITLE
Upgrading Swift Demo to Swift 3

### PR DESCRIPTION
**Pull request by aforward**
I was attempting to integrate into a iOS app, and ran into some compiler errors and warnings.  I am very fresh to Swift (like hours fresh), so here is what I did:

1) Applied the automatic conversion as available within XCode
2) Applied the automatic upgrade to "suggested" settings
3) Did my best to try and make the code work again, and work as expected.

screen shot 2017-06-08 at 11 39 28 am

It compiles now! 

```
XCode: Version 8.3.3 (8E3004b)
Swift: 3 (I think)
```

### CODE REVIEW

**Comment by gks** [comment]
Hi @aforward 

Thanks for looking into this. We have another branch called [`new/ios10`](https://github.com/agilebits/onepassword-app-extension/tree/new/ios10)

This probably needs some minor updating but might have some of your work done for you.

I suspect we'll end up prepping for Swift 4 soon, and then we'll make sure to update `master` to be in lock step with that for demos.

**Comment by aforward** [comment]
Nice!  I'll hope over to that branch to see other things to help with my integration.   Feel free to close this

**Comment by hayeuanh1986** [comment]
Subscriptions

**Comment by gks** [comment]
I'm closing this one as I have an upcoming PR that will update it to Swift 4, for both of the included Swift projects. I did use some of your changes as inspiration for the upcoming PR though :) So thank you for doing this!

**Pull request closed without merging**
