### PR TITLE
Fix "Declaration shadows a local variable" warning

### PR DESCRIPTION
**Pull request by JGiola**
This method has two instances called `error` and if a very strict warning policy is set for the project it will likely trigger a warning or an error if the developer is using the treat warning as error configuration.

### CODE REVIEW

**Comment by radazzouz** [comment]
Hi @JGiola,

Thanks for taking the time to submit a PR :+1:

Can you please tell us which is the strict warning policy that you're using in your project? It is likely that this change needs to be applied in more methods. You only made the change for `findLoginForURLString:`. If we decide to make the change, we might as well make it throughout the entire code base.

Have an amazing weekend!

**Comment by JGiola** [comment]
It's the -Wshadow clang attribute or the GCC_WARN_SHADOW option in the project setting.
In fact I've corrected only the error that is triggered by the OnePasswordExtension class (and at least in my Xcode settings is the only one that is triggered), but I haven't check in the demo projects.

**Comment by radazzouz** [comment]
Hi @JGiola,

We have the same situation for the **ACME Browser** target where the `NSError` variables are shadowed. More precisely in `- (void)fillLoginIntoWKWebView:(WKWebView *)webView forViewController:(UIViewController *)viewController sender:(id)sender completion:(void (^)(BOOL success, NSError *error))completion` and in `- (void)fillLoginIntoUIWebView:(UIWebView *)webView webViewController:(UIViewController *)viewController sender:(id)sender completion:(void (^)(BOOL success, NSError *error))completion`

Can you please make the necessary changes?

Cheers!

**Comment by JGiola** [comment]
I've enable all the warning settings that people can have enable in their project if they follow the "Xcode hard mode" configuration.
And I have fix all the warnings that Xcode has showed me in both the demo project.
I leave only the one that says that in the xcassets files there are two images that aren't assigned to anything because I don't know if I can remove them.

**Comment by radazzouz** [comment]
Hi @JGiola,

We do not want to force developers to use all the warning settings when the integrate with the 1Password App Extension API.

This PR should only address the shadowed error variables.

Thanks!

**Comment by radazzouz** [comment]
Hi @JGiola,

I just merged PR #165 which basically does what you had suggested in your first commit and which closed this PR.

Thanks for the help buddy!

**Comment by JGiola** [comment]
Sorry for the delay but in this two days I was a little busy preparing a small speech.
I don't understand why you don't want to turn on more strict warning detection in the two example projects.
People has to only copy the OnePasswordExtension .h and .m files and those do not carry around all the warning settings of the demo projects.
I am missing something? I ask only because this is my first ever pull request and I want to do a better job the next time :)

**Pull request closed without merging**
