### PR TITLE
Add framework support

### PR DESCRIPTION
**Pull request by rudyrichter**
This PR adds support for building a framework version of the extension support.

### CODE REVIEW

**Comment by rudyrichter** [comment]
@Sidetalker and @felixrosenvik we'll probably move this forward from 1.8.3, but i think most everything here looks ok to me. I would like to see if there is anyone that isn't interested in using this as a framework and that it still works as a source include for those developers.

**Comment by mccarron** [comment]
Since I use this as a Cocoapod would love to see it be updated to a Framework as adding support for Swift Package Manager should be easy then.

Can this warning fix #423 also get included in the release?

**Comment by ksullivan1-chwy** [comment]
@rudyrichter any update here? Still hoping to see this merged in. This shouldn't impact anyone who wants to continue using source code. I'm happy to contribute SPM support once this is in!

**Comment by dvshelley** [comment]
Are you going to merge this PR or make a framework/1.8.6 tag?

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.

**Pull request closed without merging**
