### PR TITLE
Support for iOS 7 target app that also uses WKWebView

### PR DESCRIPTION
**Pull request by spenrose**
This enables support of iOS7 targeted apps that use WKWebViews for
people on iOS 8 and UIWebViews for people on iOS 7.

### CODE REVIEW

**Comment by radazzouz** [comment]
Hi @spenrose,

Thanks for taking the time to reach out to us :+1: 

I am not sure I fully understand your change or I may be missing something.

It seems that you are applying the changes described in the [Projects supporting iOS 7.1 and earlier](https://github.com/AgileBits/onepassword-app-extension#projects-supporting-ios-71-and-earlier) section of the README.

Please note that our demo apps should reflect the easiest implementation possible. Which means that **ACME Browser**'s deployment target should remain iOS 8.0, therefore it should not change to iOS 7.1.

Also note that 1Password 5 for iOS (the only version that has the Extension) only runs on iOS 8 devices, which means that there will be no extension working on devices running on iOS 7.

I look forward to your reply :smile: 

Cheers!

**Comment by spenrose** [comment]
Hi @radazzouz,

The problem I am addressing is that you are doing checks on the iPhone OS version min required `if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_8_0`. If the min version is below 8.0 you are removing code from the compilation. The problem is that I can have a app that targets 7.0 and uses UIWebView for users still on 7.0 but uses WKWebViews for users on 8.0. When the users on 8.0 using WKWebViews try to use the 1password extension it will not work because there is no code to handle WKWebViews since you removed it. I am simply doing runtime checks instead to see if WKWebView class exists and if it does then we can use WKWebViews.

**Comment by radazzouz** [comment]
Hi @spenrose,

Thanks for getting back to us so quickly :+1: 

This should only happen if you are building your releases for the active architecture only and if your base SDK is lower than iOS 8.0?

Is this the case?

Thanks!

**Comment by spenrose** [comment]
Interesting. I am not sure off the top of my head. I will have to check tonight once I get home from work. I do not have that project on this computer.

**Comment by spenrose** [comment]
@radazzouz - you are correct. If I change it to build for all architectures it works correctly.

This seems like a weird choice thought since Xcode defaults Debug builds to only build with active architecture. Is there a reason not to just do run time checking to see if the class is available?

It just feels weird to have to modify my project file architecture settings to get the extension to work while I am testing. I feel this is something other people are going to run into and not know what is going on. It took some poking around in your code until I figured out why it wasn't working for me.

What do you suggest?

**Comment by radazzouz** [comment]
Hi @spenrose,

Thanks for getting back to us and I am glad that my suggestion worked out for you :wink: 

> This seems like a weird choice thought since Xcode defaults Debug builds to only build with active architecture. Is there a reason not to just do run time checking to see if the class is available?

IIRC, we did try the run-time alternative but it was throwing linker errors. As a matter of fact we do run-time checks where possible (see `- [OnePassword isSystemAppExtensionAPIAvailable]`). For this case we need to do compile-time checks.

> It just feels weird to have to modify my project file architecture settings to get the extension to work while I am testing. I feel this is something other people are going to run into and not know what is going on. It took some poking around in your code until I figured out why it wasn't working for me.

> What do you suggest?

1. Assuming that you are not distributing debug builds, I think that you are safe. Meaning that the `WKWebView` code will be included or not in the build according to the current device (hardware or simulator). Please refer to the [Projects supporting iOS 7.1 and earlier](https://github.com/AgileBits/onepassword-app-extension#projects-supporting-ios-71-and-earlier) section of the README. I applied these change in **ACME Browser** and it build fine on both iOS 7 and iOS 8 devices.

2. However, if you wish to distribute builds to other users. Meaning that you do not know on which version of iOS your app will be installed you need to build for all architectures.

3. And finally, you can always opt for the DIY approach: If the run-time checks work fine for your specific case, please feel free to alter the code locally.

I am closing this PR for now, but please feel free to reach out to us should you require more information or assistance :smile: 

Cheers!

**Comment by spenrose** [comment]
Hi @radazzouz, sorry to be annoying but I really don't think it works if you change the target below iOS 7.0.

> Assuming that you are not distributing debug builds, I think that you are safe. Meaning that the WKWebView code will be included or not in the build according to the current device (hardware or simulator). Please refer to the Projects supporting iOS 7.1 and earlier section of the README. I applied these change in ACME Browser and it build fine on both iOS 7 and iOS 8 devices.

Yes, the code will build fine but try using the 1password extension. It raises an exception saying `Invalid argument: web view must be an instance of WKWebView or UIWebView.` because you removed this code
```
#if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_8_0
	else if ([webView isKindOfClass:[WKWebView class]]) {
		[self fillLoginIntoWKWebView:webView forViewController:viewController sender:(id)sender completion:^(BOOL success, NSError *error) {
			if (completion) {
				completion(success, error);
			}
		}];
	}
#endif
```

**Pull request closed without merging**
