### PR TITLE
Remove UIWebView, update to Swift 5

### PR DESCRIPTION
**Pull request by Sidetalker**

### CODE REVIEW

**Comment by springstephen** [comment]
Will this get merged and released anytime soon?

**Comment by Sidetalker** [comment]
@springstephen the last update to the project was more than a year ago, so I'm not too hopeful 😕

**Comment by superpeteblaze** [comment]
@rudyrichter Is this project still being maintained?

**Comment by rudyrichter** [comment]
superseded by #417

**Comment by Sidetalker** [comment]
Yeehaw we back in business (except for breaking Carthage but hey, whatever)

**Review by Sarkar44 — COMMENTED** [review]
approval

**Review by bart1987laik — APPROVED** [review]

**Pull request closed without merging**
